namespace MarketMakerEtl.Core.Models.Ebay;

public sealed record ItemPageListing(
    string? ListingId,
    string? Title,
    decimal? Price,
    string? Currency,
    string? Condition,
    string? BuyingFormat,
    string? Status,
    decimal? SoldPrice,
    string? SoldDate,
    string? Seller,
    string? PrimaryImageUrl,
    string? Brand = null,
    string? Description = null,
    IReadOnlyList<string>? ImageUrls = null,
    decimal? ShippingCost = null,
    decimal? OriginalPrice = null,
    DateTimeOffset? PostedUtc = null,
    int? Likes = null,
    int? CategoryId = null,
    MercariCategoryHierarchy? CategoryHierarchy = null,
    int? BrandId = null,
    int? ConditionId = null,
    string? SizeName = null,
    string? ColorName = null,
    string? ShippingPayer = null,
    string? ShipsFromState = null,
    int? DiscountRatio = null,
    MercariSellerProfile? SellerProfile = null,
    IReadOnlyDictionary<string, string>? Attributes = null,
    string? RawJson = null);
