namespace MarketMakerEtl.Core.Models.Ebay;

public sealed record ListingSummary(
    string ListingId,
    string? Title,
    decimal? Price,
    string? Currency,
    string? Url,
    bool IsSold,
    string? Condition,
    string? PrimaryImageUrl,
    string? BuyingFormat,
    string? Brand = null,
    decimal? OriginalPrice = null,
    string? Category = null,
    int? Likes = null,
    IReadOnlyList<string>? ImageUrls = null,
    decimal? SoldPrice = null,
    DateTime? SoldDate = null,
    int? CategoryId = null,
    MercariCategoryHierarchy? CategoryHierarchy = null,
    int? BrandId = null,
    int? ConditionId = null,
    string? SizeName = null,
    string? ColorName = null,
    string? ShippingPayer = null,
    long? SellerId = null,
    IReadOnlyDictionary<string, string>? Attributes = null,
    string? RawJson = null);
