// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddClassificationBatchRuns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ClassificationBatchRuns",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    RanUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    Succeeded = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ClassificationBatchRuns", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ClassificationBatchRuns_RanUtc",
                table: "ClassificationBatchRuns",
                column: "RanUtc");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ClassificationBatchRuns");
        }
    }
}
