// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddListingClassifications : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ListingClassifications",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ListingEntityId = table.Column<int>(type: "INTEGER", nullable: false),
                    TaxonomyVersionId = table.Column<int>(type: "INTEGER", nullable: false),
                    Question = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    Choice = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    ResolvedChoice = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                    IsApplicable = table.Column<bool>(type: "INTEGER", nullable: false),
                    Confidence = table.Column<double>(type: "REAL", nullable: false),
                    Agreement = table.Column<double>(type: "REAL", nullable: false),
                    ProbabilitiesJson = table.Column<string>(type: "TEXT", nullable: false),
                    Source = table.Column<int>(type: "INTEGER", nullable: false),
                    ClassifiedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ListingClassifications", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ListingClassifications_Listings_ListingEntityId",
                        column: x => x.ListingEntityId,
                        principalTable: "Listings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ListingClassifications_TaxonomyVersions_TaxonomyVersionId",
                        column: x => x.TaxonomyVersionId,
                        principalTable: "TaxonomyVersions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ListingClassifications_ListingEntityId_Question",
                table: "ListingClassifications",
                columns: new[] { "ListingEntityId", "Question" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ListingClassifications_TaxonomyVersionId_Question_ResolvedChoice",
                table: "ListingClassifications",
                columns: new[] { "TaxonomyVersionId", "Question", "ResolvedChoice" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ListingClassifications");
        }
    }
}
