// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddDealSettingsAndSignals : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "DealGroupBy",
                table: "ProductFamilies",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "DealMinDiscount",
                table: "ProductFamilies",
                type: "TEXT",
                nullable: false,
                defaultValue: 0.20m);

            migrationBuilder.AddColumn<int>(
                name: "DealMinSold",
                table: "ProductFamilies",
                type: "INTEGER",
                nullable: false,
                defaultValue: 5);

            migrationBuilder.CreateTable(
                name: "DealSignals",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ListingEntityId = table.Column<int>(type: "INTEGER", nullable: false),
                    ProductFamilyId = table.Column<int>(type: "INTEGER", nullable: false),
                    TaxonomyVersionId = table.Column<int>(type: "INTEGER", nullable: false),
                    GroupKeyJson = table.Column<string>(type: "TEXT", nullable: false),
                    LandedPrice = table.Column<decimal>(type: "TEXT", nullable: false),
                    SoldNetMedian = table.Column<decimal>(type: "TEXT", nullable: true),
                    SoldCount = table.Column<int>(type: "INTEGER", nullable: false),
                    SoldP25 = table.Column<decimal>(type: "TEXT", nullable: true),
                    Discount = table.Column<decimal>(type: "TEXT", nullable: false),
                    CreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DealSignals", x => x.Id);
                    table.ForeignKey(
                        name: "FK_DealSignals_Listings_ListingEntityId",
                        column: x => x.ListingEntityId,
                        principalTable: "Listings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DealSignals_ProductFamilies_ProductFamilyId",
                        column: x => x.ProductFamilyId,
                        principalTable: "ProductFamilies",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DealSignals_TaxonomyVersions_TaxonomyVersionId",
                        column: x => x.TaxonomyVersionId,
                        principalTable: "TaxonomyVersions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DealSignals_ListingEntityId_LandedPrice",
                table: "DealSignals",
                columns: new[] { "ListingEntityId", "LandedPrice" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_DealSignals_ProductFamilyId_CreatedUtc",
                table: "DealSignals",
                columns: new[] { "ProductFamilyId", "CreatedUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_DealSignals_TaxonomyVersionId",
                table: "DealSignals",
                column: "TaxonomyVersionId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DealSignals");

            migrationBuilder.DropColumn(
                name: "DealGroupBy",
                table: "ProductFamilies");

            migrationBuilder.DropColumn(
                name: "DealMinDiscount",
                table: "ProductFamilies");

            migrationBuilder.DropColumn(
                name: "DealMinSold",
                table: "ProductFamilies");
        }
    }
}
