// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddTrades : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Trades",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    DealSignalId = table.Column<int>(type: "INTEGER", nullable: true),
                    ListingEntityId = table.Column<int>(type: "INTEGER", nullable: true),
                    ProductFamilyId = table.Column<int>(type: "INTEGER", nullable: true),
                    PriceGroupKeyJson = table.Column<string>(type: "TEXT", nullable: true),
                    BoughtUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    BuyPrice = table.Column<decimal>(type: "TEXT", nullable: false),
                    BuyShipping = table.Column<decimal>(type: "TEXT", nullable: false),
                    BuyFees = table.Column<decimal>(type: "TEXT", nullable: false),
                    SoldUtc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    SellPrice = table.Column<decimal>(type: "TEXT", nullable: true),
                    SellShipping = table.Column<decimal>(type: "TEXT", nullable: true),
                    SellFees = table.Column<decimal>(type: "TEXT", nullable: true),
                    Status = table.Column<int>(type: "INTEGER", nullable: false),
                    Notes = table.Column<string>(type: "TEXT", nullable: true),
                    CreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Trades", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Trades_DealSignals_DealSignalId",
                        column: x => x.DealSignalId,
                        principalTable: "DealSignals",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_Trades_Listings_ListingEntityId",
                        column: x => x.ListingEntityId,
                        principalTable: "Listings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_Trades_ProductFamilies_ProductFamilyId",
                        column: x => x.ProductFamilyId,
                        principalTable: "ProductFamilies",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Trades_CreatedUtc",
                table: "Trades",
                column: "CreatedUtc");

            migrationBuilder.CreateIndex(
                name: "IX_Trades_DealSignalId",
                table: "Trades",
                column: "DealSignalId");

            migrationBuilder.CreateIndex(
                name: "IX_Trades_ListingEntityId",
                table: "Trades",
                column: "ListingEntityId");

            migrationBuilder.CreateIndex(
                name: "IX_Trades_ProductFamilyId",
                table: "Trades",
                column: "ProductFamilyId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Trades");
        }
    }
}
