// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddProductFamiliesAndTaxonomyVersions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ProductFamilyId",
                table: "ScrapeJobs",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "ProductFamilies",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Key = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false),
                    ModelName = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false),
                    CreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProductFamilies", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "TaxonomyVersions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ProductFamilyId = table.Column<int>(type: "INTEGER", nullable: false),
                    Version = table.Column<int>(type: "INTEGER", nullable: false),
                    QuestionsJson = table.Column<string>(type: "TEXT", nullable: false),
                    CreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TaxonomyVersions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TaxonomyVersions_ProductFamilies_ProductFamilyId",
                        column: x => x.ProductFamilyId,
                        principalTable: "ProductFamilies",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ScrapeJobs_ProductFamilyId",
                table: "ScrapeJobs",
                column: "ProductFamilyId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductFamilies_Key",
                table: "ProductFamilies",
                column: "Key",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_TaxonomyVersions_ProductFamilyId_Version",
                table: "TaxonomyVersions",
                columns: new[] { "ProductFamilyId", "Version" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_ScrapeJobs_ProductFamilies_ProductFamilyId",
                table: "ScrapeJobs",
                column: "ProductFamilyId",
                principalTable: "ProductFamilies",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ScrapeJobs_ProductFamilies_ProductFamilyId",
                table: "ScrapeJobs");

            migrationBuilder.DropTable(
                name: "TaxonomyVersions");

            migrationBuilder.DropTable(
                name: "ProductFamilies");

            migrationBuilder.DropIndex(
                name: "IX_ScrapeJobs_ProductFamilyId",
                table: "ScrapeJobs");

            migrationBuilder.DropColumn(
                name: "ProductFamilyId",
                table: "ScrapeJobs");
        }
    }
}
