// <auto-generated />
using System;
using MarketMakerEtl.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    [DbContext(typeof(EtlDbContext))]
    [Migration("20260925024945_AddSegmentationSellersAndRawData")]
    partial class AddSegmentationSellersAndRawData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.JobCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScrapeJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ScrapeJobId", "CategoryId")
                        .IsUnique();

                    b.ToTable("JobCategories", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ListingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuyingFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Category0Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category0Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Category1Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category1Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Category2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category2Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConditionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetailFetchAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetailFetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscountRatio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Marketplace")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScrapeJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seller")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingPayer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipsFromState")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SoldPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.HasIndex("ScrapeJobId");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ListingRawDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ItemDetailJsonGzip")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("ItemDetailJsonUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListingEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SearchItemJsonGzip")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("SearchItemJsonUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListingEntityId")
                        .IsUnique();

                    b.ToTable("ListingRawData", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ListingStatusChangeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListingEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SoldDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListingEntityId");

                    b.ToTable("ListingStatusChanges");
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.SchedulerStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastListingRefreshUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchedulerState", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ScrapeJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterInstructions")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastQueuedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Marketplace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchTerm");

                    b.ToTable("ScrapeJobs", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ScrapeRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackfillItemPageFetches")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListingsAddedActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListingsAddedSold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListingsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListingsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListingsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Marketplace")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SearchCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalListingsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalReportedBySearch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Manual");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ScrapeRuns", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ScrapeRunIssueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScrapeRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeRunId");

                    b.ToTable("ScrapeRunIssues", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.SellerEntity", b =>
                {
                    b.Property<long>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AccountCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsProSeller")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumSales")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumSellItems")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RatingAverage")
                        .HasColumnType("REAL");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers", (string)null);
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.JobCategoryEntity", b =>
                {
                    b.HasOne("MarketMakerEtl.Core.Data.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketMakerEtl.Core.Data.Entities.ScrapeJobEntity", "ScrapeJob")
                        .WithMany("JobCategories")
                        .HasForeignKey("ScrapeJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ScrapeJob");
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ListingRawDataEntity", b =>
                {
                    b.HasOne("MarketMakerEtl.Core.Data.Entities.ListingEntity", null)
                        .WithOne("RawData")
                        .HasForeignKey("MarketMakerEtl.Core.Data.Entities.ListingRawDataEntity", "ListingEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ListingStatusChangeEntity", b =>
                {
                    b.HasOne("MarketMakerEtl.Core.Data.Entities.ListingEntity", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ListingEntity", b =>
                {
                    b.Navigation("RawData");
                });

            modelBuilder.Entity("MarketMakerEtl.Core.Data.Entities.ScrapeJobEntity", b =>
                {
                    b.Navigation("JobCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
