// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddDealSignalBacktestFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "EvaluationWindowDays",
                table: "DealSignals",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "ForwardNetMedian",
                table: "DealSignals",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "ForwardSoldCount",
                table: "DealSignals",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<double>(
                name: "ListingSoldWithinHours",
                table: "DealSignals",
                type: "REAL",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "RealisedMargin",
                table: "DealSignals",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "UsedEstimatedDates",
                table: "DealSignals",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "EvaluationWindowDays",
                table: "DealSignals");

            migrationBuilder.DropColumn(
                name: "ForwardNetMedian",
                table: "DealSignals");

            migrationBuilder.DropColumn(
                name: "ForwardSoldCount",
                table: "DealSignals");

            migrationBuilder.DropColumn(
                name: "ListingSoldWithinHours",
                table: "DealSignals");

            migrationBuilder.DropColumn(
                name: "RealisedMargin",
                table: "DealSignals");

            migrationBuilder.DropColumn(
                name: "UsedEstimatedDates",
                table: "DealSignals");
        }
    }
}
