// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddListingStatusAndSaleFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ItemStatus",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Seller",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "SoldDate",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "SoldPrice",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "ListingStatusChanges",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ListingEntityId = table.Column<int>(type: "INTEGER", nullable: false),
                    Status = table.Column<string>(type: "TEXT", nullable: false),
                    ChangedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ListingStatusChanges", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ListingStatusChanges_Listings_ListingEntityId",
                        column: x => x.ListingEntityId,
                        principalTable: "Listings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ListingStatusChanges_ListingEntityId",
                table: "ListingStatusChanges",
                column: "ListingEntityId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ListingStatusChanges");

            migrationBuilder.DropColumn(
                name: "ItemStatus",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Seller",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "SoldDate",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "SoldPrice",
                table: "Listings");
        }
    }
}
