// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    /// <inheritdoc />
    internal partial class AddListingDetailAndPriceHistory : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Category",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DescriptionStatus",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "DetailFetchedUtc",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ImageUrls",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Likes",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "OriginalPrice",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "PostedUtc",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "ShippingCost",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "Price",
                table: "ListingStatusChanges",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "SoldDateUtc",
                table: "ListingStatusChanges",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Source",
                table: "ListingStatusChanges",
                type: "TEXT",
                nullable: false,
                defaultValue: "StatusUpdate");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Category",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Description",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "DescriptionStatus",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "DetailFetchedUtc",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "ImageUrls",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Likes",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "OriginalPrice",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "PostedUtc",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "ShippingCost",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Price",
                table: "ListingStatusChanges");

            migrationBuilder.DropColumn(
                name: "SoldDateUtc",
                table: "ListingStatusChanges");

            migrationBuilder.DropColumn(
                name: "Source",
                table: "ListingStatusChanges");
        }
    }
}
