// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    internal partial class AddSegmentationSellersAndRawData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Attributes",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "BrandId",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Category0Id",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Category0Name",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Category1Id",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Category1Name",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Category2Id",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Category2Name",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "CategoryId",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ColorName",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "ConditionId",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DiscountRatio",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "SellerId",
                table: "Listings",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ShippingPayer",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ShipsFromState",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "SizeName",
                table: "Listings",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "ListingRawData",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ListingEntityId = table.Column<int>(type: "INTEGER", nullable: false),
                    SearchItemJsonGzip = table.Column<byte[]>(type: "BLOB", nullable: true),
                    ItemDetailJsonGzip = table.Column<byte[]>(type: "BLOB", nullable: true),
                    SearchItemJsonUpdatedUtc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    ItemDetailJsonUpdatedUtc = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ListingRawData", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ListingRawData_Listings_ListingEntityId",
                        column: x => x.ListingEntityId,
                        principalTable: "Listings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Sellers",
                columns: table => new
                {
                    SellerId = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    NumSales = table.Column<int>(type: "INTEGER", nullable: true),
                    NumSellItems = table.Column<int>(type: "INTEGER", nullable: true),
                    RatingCount = table.Column<int>(type: "INTEGER", nullable: true),
                    RatingAverage = table.Column<double>(type: "REAL", nullable: true),
                    IsProSeller = table.Column<bool>(type: "INTEGER", nullable: true),
                    AccountCreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: true),
                    LastSeenUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Sellers", x => x.SellerId);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ListingRawData_ListingEntityId",
                table: "ListingRawData",
                column: "ListingEntityId",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ListingRawData");

            migrationBuilder.DropTable(
                name: "Sellers");

            migrationBuilder.DropColumn(
                name: "Attributes",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "BrandId",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Category0Id",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Category0Name",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Category1Id",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Category1Name",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Category2Id",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "Category2Name",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "CategoryId",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "ColorName",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "ConditionId",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "DiscountRatio",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "SellerId",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "ShippingPayer",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "ShipsFromState",
                table: "Listings");

            migrationBuilder.DropColumn(
                name: "SizeName",
                table: "Listings");
        }
    }
}
