// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketMakerEtl.Core.Data.Migrations
{
    internal partial class AddRunTriggerCountersAndIssues : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "DetailCompletedUtc",
                table: "ScrapeRuns",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "ListingsAddedActive",
                table: "ScrapeRuns",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "ListingsAddedSold",
                table: "ScrapeRuns",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "ListingsFailed",
                table: "ScrapeRuns",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "ListingsSkipped",
                table: "ScrapeRuns",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "ListingsUpdated",
                table: "ScrapeRuns",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "SearchCompletedUtc",
                table: "ScrapeRuns",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "TotalListingsFound",
                table: "ScrapeRuns",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "TotalReportedBySearch",
                table: "ScrapeRuns",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "TriggerType",
                table: "ScrapeRuns",
                type: "TEXT",
                maxLength: 32,
                nullable: false,
                defaultValue: "Manual");

            migrationBuilder.CreateTable(
                name: "ScrapeRunIssues",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ScrapeRunId = table.Column<int>(type: "INTEGER", nullable: false),
                    ListingId = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                    IssueType = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    ErrorMessage = table.Column<string>(type: "TEXT", maxLength: 2000, nullable: false),
                    Phase = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false),
                    HttpStatusCode = table.Column<int>(type: "INTEGER", nullable: true),
                    CreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ScrapeRunIssues", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ScrapeRunIssues_ScrapeRunId",
                table: "ScrapeRunIssues",
                column: "ScrapeRunId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ScrapeRunIssues");

            migrationBuilder.DropColumn(
                name: "DetailCompletedUtc",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "ListingsAddedActive",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "ListingsAddedSold",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "ListingsFailed",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "ListingsSkipped",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "ListingsUpdated",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "SearchCompletedUtc",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "TotalListingsFound",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "TotalReportedBySearch",
                table: "ScrapeRuns");

            migrationBuilder.DropColumn(
                name: "TriggerType",
                table: "ScrapeRuns");
        }
    }
}
